config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  # C[R]UD
  get "tasks", to: 'tasks#index'
  # [C]RUD
  get "tasks/new", to: "tasks#new", as: :new
  # C[R]UD
  get "tasks/:id", to: 'tasks#show', as: :task
  # [C]RUD
  post "tasks/", to: "tasks#create"
  # CR[U]D
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  # CR[U]D
  patch "tasks/:id", to: "tasks#update"
  #CRU[D]
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update!(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task.delete
    redirect_to root_path
  end

  private

  def task_params
    params.require("task").permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>
  <button class="btn"><%= link_to "Back to list", tasks_path %></button>
</div>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

<div class="container">
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-counterclockwise" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M8 3a5 5 0 1 1-4.546 2.914.5.5 0 0 0-.908-.417A6 6 0 1 0 8 2v1z"/>
  <path d="M8 4.466V.534a.25.25 0 0 0-.41-.192L5.23 2.308a.25.25 0 0 0 0 .384l2.36 1.966A.25.25 0 0 0 8 4.466z"/>
</svg> 
</div>

app/views/tasks/index.html.erb
<div class="container">
  <section class="header">
    <h1>Tasks</h1>
  </section>
  <section class="content">
    <% @tasks.each do |task| %>
      <% if task.completed %>
      <div class="task d-flex flex-row-reverse">
        <input type="checkbox" style="margin: 8px" name="title" checked>
        <label for="title"> <%= link_to task.title, task_path(task) %> </label><br>
      </div>
      <% else %>
      <div class="task d-flex flex-row-reverse">
        <input type="checkbox" style="margin: 8px" name="title">
        <label for="title"> <%= link_to task.title, task_path(task) %> </label><br>
      </div>
      <% end %>
    <% end %>
  
    <button type="button" class="btn btn-primary"><%= link_to "Create new task", new_path %></button>
    <%# <%= link_to "+ Add a new task", %>
  </section>
</div>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div class="container">

  <h1><%= @task.title %></h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page"><%= @task.details %></li>
    </ol>
  </nav>

  <% if @task.completed %>
    <input type="checkbox" name="title" checked>
    <label for="title">This task is completed</label><br>
    <hr>
  <% else %>
    <input type="checkbox" name="title">
    <label for="title">This task is not completed</label><br>
    <hr>
  <% end %>

  <button type="button" class="btn btn-primary"><%= link_to "Back to list", root_path %></button>
  <button type="button" class="btn btn-primary"><%= link_to "Edit item", edit_path %></button>
  <button type="button" class="btn btn-primary"><%= link_to "Delete item", task_path(@task), method: :delete, data: { confirm: "Are you sure?"} %></button>
  

</div>